version: "3"
services: 
    proxy:
        build: 
            context: ./Proxy
            dockerfile: Dockerfile
        ports: 
            - "80:80"
        restart: always
    client:
        build:
            context: ./angularCalendarApp
            dockerfile: Dockerfile
        ports: 
            - "9000:80"
    api:
        build: 
            context: ./CalendarApp1
            dockerfile: Dockerfile
        ports: 
            - "5000:80"
  #  mongo:
  #      build: 
  #          context: ./Mongo
  #          dockerfile: Dockerfile
  #      ports: 
  #          - "4000:80"

